Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public int MachineId { get; set; }
    public string MachineName { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;
    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Machines.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine, int EngineerId)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      if(EngineerId !=0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = machine.MachineId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
      .Include(machine => machine.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
          var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
          ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
          return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine, int EngineerId)
    {
      if (EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = machine.MachineId});
      }
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int EngineerId)
    {
      if(EngineerId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {EngineerId = EngineerId, MachineId = machine.MachineId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteEngineer(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Add a machine</h3>
<hr>

<h4>Add an engineer @Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName) for: </h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  <div class="form-group">
    @Html.Label("Select engineer")
    @Html.DropDownList("EngineerId", null, new {@class = "form-control"})
  </div>
  <br>
  <input type = "submit" value="Save" class = "btn btn-dark"/>
}
<br>
<p class="btn btn-outline-dark">@Html.ActionLink("Back to machines", "Index")</p>
<p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Add a new machine</h3>
<hr>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.TextBoxFor(model => model.MachineName, new {@class = "form-control", @required = "required"})
  <input type = "submit" value = "Add new machine" class="btn btn-dark"/>
}

<p class="btn btn-outline-dark">@Html.ActionLink("Show all machines", "Index")</p>
<p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Delete @Html.DisplayFor(model => model.MachineName)?</h2>

@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-dark"/>
}

<p class="btn btn-dark">@Html.ActionLink("Back to Machines", "Index")</p>
<p class="btn btn-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h3>Machine Details</h3>
<hr>
<h3>@Html.DisplayNameFor(model => model.MachineName): @Html.DisplayFor(model => model.MachineName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine has no engineers</p>
}
else
{
  <h4>Engineers licensed for this machine</h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Engineer.EngineerName</li>
      @using(Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" class="btn btn-dark"/>
      }
    }
  </ul>
}
  <p class="btn btn-outline-dark">@Html.ActionLink("Add a new machine", "Create")</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Edit machine", "Edit", new {id = Model.MachineId})</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Add an existing engineer", "AddEngineer", new {id = Model.MachineId})</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Delete machine", "Delete", new {id = Model.MachineId})</p>
  
  <p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Edit this machine: @Html.DisplayFor(model => model.MachineName)</h3>
<hr>

@using(Html.BeginForm())
{
  <div class = "form-group">
    @Html.HiddenFor(model => model.MachineId)
    <p>Machine @Html.LabelFor(model => model.MachineName)
    @Html.EditorFor(model => model.MachineName, new {@class = "form-control"})</p>
  </div>
  <input type="submit" value = "Save" class = "btn btn-primary" />
}
<br>
<p class="btn btn-dark">@Html.ActionLink("Back to machines", "Index")</p>
<p class="btn btn-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="jumobtron jumobtron=fluid">
  <h1>Machines</h1>
</div>

@if (Model.Count == 0)
{
  <h3>No machines have been added yet!</h3>
}

<ul>
  @foreach(Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.MachineName}", "Details", new{id =machine.MachineId})</li>
  }
</ul>
  <p class="btn btn-outline-dark">@Html.ActionLink("Add a new machine", "Create")</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>