Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }
    public int EngineerId { get; set; }
    public string EngineerName { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;
    public EngineersController(FactoryContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }
    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if(MachineId !=0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
      .Include(engineer => engineer.JoinEntities)
      .ThenInclude(join => join.Machine)
      .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
          var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
          ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
          return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if(MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() {MachineId = MachineId, EngineerId = engineer.EngineerId});
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Add a machine</h3>
<hr>

<h4>Add a machine @Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName) for: </h4>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  <div class="form-group">
    @Html.Label("Select machine")
    @Html.DropDownList("MachineId", null, new {@class = "form-control"})
  </div>
  <br>
  <input type = "submit" value="Save" class = "btn btn-dark"/>
}
<br>
<p class="btn btn-outline-dark">@Html.ActionLink("Back to engineers", "Index")</p>
<p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Hire an engineer</h3>
<hr>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName)
  @Html.TextBoxFor(model => model.EngineerName, new {@class = "form-control", @required = "required"})
  <input type = "submit" value = "Hire new engineer" class="btn btn-dark"/>
}

<p class="btn btn-outline-dark">@Html.ActionLink("Show all engineers", "Index")</p>
<p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Delete @Html.DisplayFor(model => model.EngineerName)?</h2>

@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-dark"/>
}

<p class="btn btn-dark">@Html.ActionLink("Back to Engineers", "Index")</p>
<p class="btn btn-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer;

<h3>Machine Details</h3>
<hr>
<h3>@Html.DisplayNameFor(model => model.EngineerName): @Html.DisplayFor(model => model.EngineerName)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This engineer is not assigned to any machines</p>
}
else
{
  <h4>Machines this engineer is licensed for: </h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Machine.MachineName</li>
      @using(Html.BeginForm("DeleteMachine", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" class="btn btn-dark"/>
      }
    }
  </ul>
}
  <p class="btn btn-outline-dark">@Html.ActionLink("Hire a new engineer", "Create")</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Edit engineer", "Edit", new {id = Model.EngineerId})</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Add an existing machine", "AddMachine", new {id = Model.EngineerId})</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Delete engineer", "Delete", new {id = Model.EngineerId})</p>
  
  <p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Edit this engineer: @Html.DisplayFor(model => model.EngineerName)</h3>
<hr>

@using(Html.BeginForm())
{
  <div class = "form-group">
    @Html.HiddenFor(model => model.EngineerId)
    <p>Machine @Html.LabelFor(model => model.EngineerName)
    @Html.EditorFor(model => model.EngineerName, new {@class = "form-control"})</p>
  </div>
  <input type="submit" value = "Save" class = "btn btn-primary" />
}
<br>
<p class="btn btn-dark">@Html.ActionLink("Back to engineer", "Index")</p>
<p class="btn btn-dark">@Html.ActionLink("Home", "Index", "Home")</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<div class="jumobtron jumobtron=fluid">
  <h1>Engineers</h1>
</div>

@if (Model.Count == 0)
{
  <h3>No engineers have been hired yet!</h3>
}

<ul>
  @foreach(Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new{id =engineer.EngineerId})</li>
  }
</ul>
  <p class="btn btn-outline-dark">@Html.ActionLink("Hire an engineer", "Create")</p>
  <p class="btn btn-outline-dark">@Html.ActionLink("Home", "Index", "Home")</p>